{
 "title": "Student 3 dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "Broj trenutno aktivnih korisnika u toku 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(application_active_users[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prosečno zauzeće CPU u određenom vremenskom intervalu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(system_cpu_usage[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prosečno trajanje HTTP zahteva za kreiranje nove objave u toku 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"POST\", outcome=\"SUCCESS\", status=\"200\", uri=\"/api/posts/createpost/{profileId}\"}[24h])/rate(http_server_requests_seconds_count{method=\"POST\", outcome=\"SUCCESS\", status=\"200\", uri=\"/api/posts/createpost/{profileId}\"}[24h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}